name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8' # You can adjust this to your Java version

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

    - name: Build Maven project
      run: mvn clean install -f pom.xml

    - name: Retry on Failure
      run: |
        if [ $? -ne 0 ]; then
          echo "Retrying the build..."
          mvn clean install -f pom.xml
        fi

    - name: Deploy to Dev Environment
      run: |
        sudo mkdir -p /home/osanda/Desktop/Dev/wso2mi-4.2.0/repository/deployment/server/carbonapps
        sudo cp TestInt2CompositeExporter/target/*.car /home/osanda/Desktop/Dev/wso2mi-4.2.0/repository/deployment/server/carbonapps

    - name: Deploy to Test Environment
      run: |
        sudo mkdir -p /home/osanda/Desktop/Test/wso2mi-4.2.0/repository/deployment/server/carbonapps
        sudo cp TestInt2CompositeExporter/target/*.car /home/osanda/Desktop/Test/wso2mi-4.2.0/repository/deployment/server/carbonapps
       
