name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main
    paths:
      - 'TestInt2CompositeExporter/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

    - name: Build Maven project
      run: mvn clean install -f pom.xml

    - name: Copy CAR files to ${{ github.workspace }}/artifacts
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        find . -type f -name "*.car" -exec cp {} ${{ github.workspace }}/artifacts \;

    - name: Print CAR files in ${{ github.workspace }}/artifacts
      run: |
        ls ${{ github.workspace }}/artifacts

    - name: Copy CAR files to another repo
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.OsandaW }}
      with:
        source_file: './TestInt2CompositeExporter/target/TestInt2CompositeExporter_1.0.0.car'
        destination_repo: 'OsandaDhananjaya/wso2mi'
        destination_folder: 'repository/deployment/server/carbonapps'
        user_name: 'osandaDhananjaya'
        commit_message: 'Copy CAR file from TestInt2CompositeExporter'
