name: Build and Deploy Carbon App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 8 # You can change this to the desired Java version

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '3.6.3' # Use the specific Maven version you need

      - name: Build with Maven
        run: |
          mvn clean install -X
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository" # Customize this as needed

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: carbon-app-artifact
          path: TestInt2CompositeExporter/target/*.car
