name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main
    paths:
      - 'TestInt2CompositeExporter/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

      - name: Build Maven project
        run: mvn clean install -f pom.xml

      - name: Upload Artifacts 
        uses: actions/upload-artifact@v2   
        with:     
          name: TestInt2CompositeExporter_1.0.0.car   
          path: ${{ github.workspace }}/TestInt2CompositeExporter/targettest

  CopyCarbonApps:
    name: Collect artifact and send to image repo
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts 

      - name: Push to docker droppings dir
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.OsandaW }}
        with:
          source_file: './TestInt2CompositeExporter/target/TestInt2CompositeExporter_1.0.0.car' 
          destination_repo: 'OsandaDhananjaya/wso2mi' 
          destination_folder: 'repository/deployment/server/carbonapps'
          user_name: 'osandaDhananjaya'
