name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11' # You can adjust this to your Java version

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}
        

    - name: Build Maven project
      run: mvn clean install -f TestInt2CompositeExporter/pom.xml

    - name: Retry on Failure
      run: |
        if [ $? -ne 0 ]; then
          echo "Retrying the build..."
          mvn clean install -f TestInt2CompositeExporter/pom.xml
        fi

    - name: Deploy to Dev Environment
      run: scp -r TestInt2CompositeExporter/target/*.car user@dev-server:/Desktop/Dev/wso2mi-4.2.0/repository/deployment/server/carbonapps
      # This step uses the `scp` command to copy the generated .car file to the Dev environment. Replace `user` and `dev-server` with your actual credentials.

    - name: Deploy to Test Environment
      run: scp -r TestInt2CompositeExporter/target/*.car user@test-server:/Desktop/Test/wso2mi-4.2.0/repository/deployment/server/carbonapps
      # This step uses the `scp` command to copy the generated .car file to the Test environment. Replace `user` and `test-server` with your actual credentials.
