name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

      - name: Build Maven project
        run: mvn clean install -f pom.xml

      - name: Copy CAR files to ${{ github.workspace }}/artifacts
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          find . -type f -name "*.car" -exec cp {} ${{ github.workspace }}/artifacts \;

      - name: Print CAR files in ${{ github.workspace }}/artifacts
        run: |
          ls ${{ github.workspace }}/artifacts

      - name: Zipping CAR files in ${{ github.workspace }}/artifacts for release
        run: |
          cd ${{ github.workspace }} && zip -r carbonapps.zip artifacts/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Carbon Application
          path: ${{ github.workspace }}/artifacts

      - name: Generate Timestamp
        id: timestamp_step
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_PAT }}
          ENVIRONMENT: "dev"
        with:
          tag_name: "${{env.ENVIRONMENT}}-${{ steps.timestamp_step.outputs.TIMESTAMP }}"   # Set the appropriate tag for your release
          release_name: "Release ${{env.ENVIRONMENT}} : ${{ steps.timestamp_step.outputs.TIMESTAMP }}"  # Set the release name
          draft: false
          prerelease: false

      - name: Attach Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/carbonapps.zip
          asset_name: carbonapps-release.zip
          asset_content_type: application/octet-stream

      # - name: Download artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build-artifacts

      - name: Push to docker droppings dir
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.MAVEN_PAT}}
        with:
          source_file: '${{ github.workspace }}/artifacts'
          destination_repo: 'OsandaDhananjaya/wso2mi'
          destination_folder: 'repository/deployment/server/carbonapps'
          user_name: 'osandaDhananjaya'
          commit_message: 'Copy CAR file from Releases'
