name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

      - name: Build Maven project
        run: mvn clean install -f pom.xml

      - name: Determine the correct destination directory
        id: set_directory
        run: |
          # This command prints the current working directory, which you can use to construct the correct path.
          echo "DEST_DIR=$(pwd)/Desktop/Test/wso2mi-4.2.0/repository/deployment/server/carbonapps/"
          echo "DEST_DIR=${DEST_DIR}" >> $GITHUB_ENV

      - name: Copy CAR files to destination directory
        run: |
          find . -type f -name "*.car" -exec cp {} ${{ env.DEST_DIR }} \;

      - name: Print CAR files in destination directory
        run: |
          ls ${{ env.DEST_DIR }}
