name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8' # You can adjust this to your Java version

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

    - name: Build Maven project
      run: mvn clean install -f pom.xml

    - name: Commit and Push Artifacts
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.382-5/x64
        GH_PAT: ${{ secrets.PAT2 }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add TestInt2CompositeExporter/target  # Replace with the actual path to your built Carbon application files
        git commit -m "Add built Carbon application"
        git push https://$PAT2@github.com/osandaDhananjaya/carbonApplication.git HEAD:main  # Replace with your GitHub username and repository name
