name: Build and Deploy Carbon Application

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the runner as needed

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Build Carbon Application
        run: |
          mvn clean install -X
        working-directory: ./  # Assuming your project's root directory contains the Maven project

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: carbon-app
          path: TestInt2CompositeExporter/target/*.car

  deploy-dev:
    runs-on: ubuntu-latest

    needs: build  # This job depends on the 'build' job

    steps:
      - name: Create Dev Directory
        run: |
          sudo mkdir -p /home/osanda/Desktop/Dev/wso2mi-4.2.0/repository/deployment/server/carbonapps
        shell: bash

      - name: Copy Artifact to Dev
        run: |
          sudo cp ${{ needs.build.outputs.artifacts_path }}/carbon-app/*.car /home/osanda/Desktop/Dev/wso2mi-4.2.0/repository/deployment/server/carbonapps
        shell: bash

  deploy-test:
    runs-on: ubuntu-latest

    needs: build  # This job depends on the 'build' job

    steps:
      - name: Create Test Directory
        run: |
          sudo mkdir -p /home/osanda/Desktop/Test/wso2mi-4.2.0/repository/deployment/server/carbonapps
        shell: bash

      - name: Copy Artifact to Test
        run: |
          sudo cp ${{ needs.build.outputs.artifacts_path }}/carbon-app/*.car /home/osanda/Desktop/Test/wso2mi-4.2.0/repository/deployment/server/carbonapps
        shell: bash
