name: Deploy Carbon App to WSO2 MI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8' # You can adjust this to your Java version

    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.xml') }}

    - name: Build Maven project
      run: mvn clean install -f pom.xml

    - name: Upload Artifacts 
      uses: actions/upload-artifact@v2   
      with:     
        name: build-artifacts   
        path: ${{ github.workspace }}/TestInt2CompositeExporter/target

    - name: Deploy Locally
      run: |
        # Create a directory for deployment if it doesn't exist
        mkdir -p ~/local-deployment
        
        # Copy the built Carbon application artifacts from the GitHub Actions artifact
        cp -r ${{ github.workspace }}/TestInt2CompositeExporter/target/* ~/local-deployment/
        
        # Assuming you have WSO2 MI installed locally, deploy the Carbon application
        cp -r ~/local-deployment/* /Desktop/Dev/wso2mi-4.2.0/repository/deployment/server/carbonapps/
